version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.2
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  test:
    docker:
      - image: circleci/node:10.15.2

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm test

  release:
    docker:
      - image: circleci/node:10.15.2

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npx semantic-release

workflows:
  version: 2
  build_test__release:
    jobs:
      - build
      - test:
          requires:
            - build
      - release_approval:
          type: approval
          filters:
            branches:
              only:
                - master
      - release:
          requires:
            - build
            - test
            - release_approval
          filters:
            branches:
              only:
                - master
